# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[ru]
 languageCode = "ru-ru"
 contentDir = "content/ru"
 [ru.params]
   description = "Простой и легковесный переводчик, который позволяет переводить и озвучивать текст с помощью Google, Yandex и Bing."
 [[ru.menu.main]]
   pre = "<i class=\"fas fa-images\"></i> "
   name = "Скриншоты"
   url = "screenshots"
   weight = 10

 [[ru.menu.main]]
   pre = "<i class=\"fas fa-keyboard\"></i> "
   name = "Горячие клавиши"
   url = "shortcuts"
   weight = 20

 [[ru.menu.main]]
   pre = "<i class=\"fas fa-terminal\"></i> "
   name = "Команды"
   url = "commands"
   weight = 30

 [[ru.menu.main]]
   pre = "<i class=\"fas fa-newspaper\"></i> "
   name = "Изменения"
   url = "https://github.com/crow-translate/crow-translate/blob/master/CHANGELOG.md"
   weight = 40
  
 [[ru.menu.main_right]]
   name = "<i class=\"fas fa-globe-americas\"></i> "
   post = "Transifex"
   url = "https://www.transifex.com/crow-translate/crow-translate/dashboard/"
   weight = 10

 [[ru.menu.main_right]]
   name = "<i class=\"fab fa-github-alt\"></i> "
   post = "GitHub"
   url = "https://github.com/crow-translate"
   weight = 20

[es]
 languageCode = "es-es"
 contentDir = "content/es"
 [es.params]
   description = "Un traductor simple y ligero que permite traducir y reproducir de manera hablada el texto utilizando Google, Yandex o Bing."
 [[es.menu.main]]
   pre = "<i class=\"fas fa-images\"></i> "
   name = "Capturas de pantalla"
   url = "screenshots"
   weight = 10

 [[es.menu.main]]
   pre = "<i class=\"fas fa-keyboard\"></i> "
   name = "Atajos de teclado"
   url = "shortcuts"
   weight = 20

 [[es.menu.main]]
   pre = "<i class=\"fas fa-terminal\"></i> "
   name = "Comandos"
   url = "commands"
   weight = 30

 [[es.menu.main]]
   pre = "<i class=\"fas fa-newspaper\"></i> "
   name = "Registro de cambios"
   url = "https://github.com/crow-translate/crow-translate/blob/master/CHANGELOG.md"
   weight = 40
 
 [[es.menu.main_right]]
   name = "<i class=\"fas fa-globe-americas\"></i> "
   post = "Transifex"
   url = "https://www.transifex.com/crow-translate/crow-translate/dashboard/"
   weight = 10

 [[es.menu.main_right]]
   name = "<i class=\"fab fa-github-alt\"></i> "
   post = "GitHub"
   url = "https://github.com/crow-translate"
   weight = 20
