name: Main
on: push
jobs:
  Deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Clone repo
      uses: actions/checkout@v2.1.0
      with:
        submodules: true

    - name: Run Hugo
      uses: crazy-max/ghaction-hugo@v1.3.1
      with:
        extended: true

    - name: Deploy to GitHub pages
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
        repo: crow-translate/crow-translate.github.io
        target_branch: master
        keep_history: true
        allow_empty_commit: false
        build_dir: public
        commit_message: ${{ github['event']['commits'][0]['message'] }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
